language: node_js
node_js:
  - "0.11"
  - "0.10"

services:
  - cassandra
  - rabbitmq
  - mysql

before_script:
  - sudo pip install cqlsh
  - cqlsh -f test/scripts/medint.cql
  - cqlsh -f test/scripts/medsafe.cql
  - sudo curl -o /usr/local/bin/rabbitmqadmin http://localhost:15672/cli/rabbitmqadmin
  - sudo chmod +x /usr/local/bin/rabbitmqadmin
  - rabbitmqadmin declare exchange name=caresharing.medintegrate type=direct durable=true
  - mysql -u root < test/scripts/schema.sql
