language: node_js
node_js:
  - "0.11"
  - "0.10"

services:
  - cassandra
  - rabbitmq

before_script:
  - sudo pip install cqlsh
  - cqlsh -f test/schema.cql
  - curl -o /tmp/rabbitmqadmin http://localhost:15672/cli/rabbitmqadmin
  - chmod +x /tmp/rabbitmqadmin
  - mv /tmp/rabbitmqadmin /usr/local/bin/
  - rabbitmqadmin declare exchange name=caresharing.medintegrate type=direct durable=true
