CREATE DATABASE IF NOT EXISTS medsafe_test;

USE medsafe_test;

DROP TABLE IF EXISTS data_points_0;
CREATE TABLE data_points_0
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  code TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS patient_profile;
CREATE TABLE patient_profile
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  system_code TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS profiles;
CREATE TABLE profiles
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  medsafe_guid TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS attributes;
CREATE TABLE attributes
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  `key` TEXT NOT NULL,
  `value` TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
