CREATE DATABASE IF NOT EXISTS medsafe;

USE medsafe;

CREATE TABLE data_points_0
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  code TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE patient_profile
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  system_code TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE profiles
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  medsafe_guid TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE attributes
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  `key` TEXT NOT NULL,
  `value` TEXT NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
